---
figures:
 - # alanine 2D
  path: ~/BOSS-MT/figures/
  filename: alanine2D_gmp_x_last
  enumerate_subplots: True
  subplots: # plot all plots in 
   - # alanine 2D HF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine2D_HF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine2D_HF_exp_
      N_experiments: 20
      use_colormap: True
    unique_experiments:
      - alanine2D_HF_baseline_ICM
    xkey: gmp
    xcol: 0
    xunit: d4
    xmin: -50
    xmax: 310
    # y
    ykey: gmp
    ycol: 1
    ybegin: -1
    yunit: d13
    ymin: -50
    ymax: 310
    # title
    title: alanine 2D HF GMP location
   - # alanine 2D LF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine2D_LF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine2D_LF_exp_
      N_experiments: 20
      use_colormap: True
    unique_experiments:
      - alanine2D_LF_baseline_ICM
    xkey: gmp
    xcol: 0
    xunit: d4
    xmin: -50
    xmax: 310
    # y
    ykey: gmp
    ycol: 1
    ybegin: -1
    yunit: d13
    ymin: -50
    ymax: 310
    # title
    title: alanine 2D LF GMP location

 - # alanine 4D HF
  path: ~/BOSS-MT/figures/
  filename: alanine4D_HF_gmp_x_last
  enumerate_subplots: True
  subplots: 
   - # alanine 4D HF d4 d13
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine4D_HF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine4D_HF_exp_
      N_experiments: 16
      use_colormap: True
    unique_experiments:
      - alanine4D_HF_baseline_ICM
    xkey: gmp
    xcol: 0
    xunit: d4
    xmin: -50
    xmax: 310
    # y
    ykey: gmp
    ycol: 3
    ybegin: -1
    yunit: d13
    ymin: -50
    ymax: 310
    # title
    title: alanine 4D HF GMP location
   - # alanine 4D HF d7 d11
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine4D_HF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine4D_HF_exp_
      N_experiments: 16
      use_colormap: True
    unique_experiments:
      - alanine4D_HF_baseline_ICM
    xkey: gmp
    xcol: 1
    xunit: d7
    xmin: -50
    xmax: 70
    # y
    ykey: gmp
    ycol: 2
    ybegin: -1
    yunit: d11
    ymin: -50
    ymax: 310
    # title
    title: alanine 4D HF GMP location

 - # alanine 4D LF
  path: ~/BOSS-MT/figures/
  filename: alanine4D_LF_gmp_x_last
  enumerate_subplots: True
  subplots:
   - # alanine 4D LF d4 d13
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine4D_LF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine4D_LF_exp_
      N_experiments: 16
      use_colormap: True
    unique_experiments:
      - alanine4D_LF_baseline_ICM
    xkey: gmp
    xcol: 0
    xunit: d4
    xmin: -50
    xmax: 310
    # y
    ykey: gmp
    ycol: 3
    ybegin: -1
    yunit: d13
    ymin: -50
    ymax: 310
    # title
    title: alanine 4D LF GMP location
   - # alanine 4D LF d7 d11
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine4D_LF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine4D_LF_exp_
      N_experiments: 16
      use_colormap: True
    unique_experiments:
      - alanine4D_LF_baseline_ICM
    xkey: gmp
    xcol: 1
    xunit: d7
    xmin: -50
    xmax: 70
    # y
    ykey: gmp
    ycol: 2
    ybegin: -1
    yunit: d11
    ymin: -50
    ymax: 310
    # title
    title: alanine 4D LF GMP location

   - # alanine 4D VHF
  path: ~/BOSS-MT/figures/
  filename: alanine4D_VHF_gmp_x_last
  enumerate_subplots: True
  subplots: 
   - # alanine 4D VHF d4 d13
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine4D_VHF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine4D_VHF_exp_
      N_experiments: 16
      use_colormap: True
    unique_experiments:
      - alanine4D_VHF_baseline_ICM
    xkey: gmp
    xcol: 0
    xunit: d4
    xmin: -50
    xmax: 310
    # y
    ykey: gmp
    ycol: 3
    ybegin: -1
    yunit: d13
    ymin: -50
    ymax: 310
    # title
    title: alanine 4D VHF GMP location
   - # alanine 4D VHF d7 d11
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine4D_VHF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine4D_VHF_exp_
      N_experiments: 16
      use_colormap: True
    unique_experiments:
      - alanine4D_VHF_baseline_ICM
    xkey: gmp
    xcol: 1
    xunit: d7
    xmin: -50
    xmax: 70
    # y
    ykey: gmp
    ycol: 2
    ybegin: -1
    yunit: d11
    ymin: -50
    ymax: 310
    # title
    title: alanine 4D VHF GMP location
