---
figures:
 - 
  path: ~/BOSS-MT/figures/
  filename: alanine2D_4D_bestacq_y_bo_iteration
  enumerate_subplots: True
  subplots: # plot all plots in 
   - # alanine 2D HF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine2D_HF_baseline
    array_experiments:
      namebase: alanine2D_HF_exp_
      N_experiments: 20
      use_colormap: True
    unique_experiments:
      - alanine2D_HF_baseline_ICM
    xunit: BO iteration
    # y
    ykey: bestacq
    ycol: -1
    yunit: eV
    # legend
    labelrule: secondary initpts
    legend: True
    legend_location: upper right
    legend_title: secondary initpts
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 2D HF best acquisition
    make_subplots: [0, 8, 14, 19, 20, 21]
   - # alanine 2D LF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine2D_LF_baseline
    array_experiments:
      namebase: alanine2D_LF_exp_
      N_experiments: 20
      use_colormap: True
    unique_experiments:
      - alanine2D_LF_baseline_ICM
    xunit: BO iteration
    # y
    ykey: bestacq
    ycol: -1
    yunit: eV
    ybegin: 1
    rescale_y: 0.04336325397
    # legend
    labelrule: secondary initpts
    legend: True
    legend_location: upper right
    legend_title: secondary initpts
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 2D LF best acquisition
    make_subplots: [0, 8, 14, 19, 20, 21]
   - # alanine 4D HF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine4D_HF_baseline
    array_experiments:
      namebase: alanine4D_HF_exp_
      N_experiments: 16
      use_colormap: True
    unique_experiments:
      - alanine4D_HF_baseline_ICM
    xunit: BO iteration
    # y
    ykey: bestacq
    ycol: -1
    yunit: eV
    # legend
    labelrule: secondary initpts
    legend: True
    legend_location: upper right
    legend_title: secondary initpts
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 4D HF best acquisition
    make_subplots: [0, 5, 10, 15, 16, 17]
   - # alanine 4D LF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine4D_LF_baseline
    array_experiments:
      namebase: alanine4D_LF_exp_
      N_experiments: 16
      use_colormap: True
    unique_experiments:
      - alanine4D_LF_baseline_ICM
    xunit: BO iteration
    # y
    ykey: bestacq
    ycol: -1
    yunit: eV
    ybegin: 1
    rescale_y: 0.04336325397
    # legend
    labelrule: secondary initpts
    legend: True
    legend_location: upper right
    legend_title: secondary initpts
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 4D LF best acquisition
    make_subplots: [0, 5, 10, 15, 16, 17]