---
# plot TL experiment results
plotnames: # under this are names of the plots
  alanine2D_TL_random_init: # name of plot
    experiments: [a3b6, a3c1, a3c2] # TL experiments
    baselines: [a1b2, a1c2, a1c2] # corresponding baselines
  alanine2D_TL_BO_init:
    experiments: [a3b7, a3c3, a3c4]
    baselines: [a1b2, a1c2, a1c2]
  alanine2D_TL_sobol_init:
    experiments: [a3b8, a3c5, a3c6]
    baselines: [a1b2, a1c2, a1c2]
  alanine4D_TL_BO_init:
    experiments: [b3b1, b3c1, b3c2]
    baselines: [b1b2, b1c2, b1c2]