---

# filename: folders
figures:
  prior_selection_convergence_random_sobol: [a1a2, a1a3]
  prior_selection_convergence_1_task: [a1a3, a2a1, a2a2, a2a3, a2a4]
  prior_selection_convergence_2_task: [a1b2, a3b1, a3b2, a3b3, a3b4, a3b5]