
---
# tabularise yaml format
tables:
 - 
  path_to_data: ~/BOSS-MT/processed_data/
  table_header: alanine2D setup
  experiments:
    single:
     - alanine2D_HF_baseline
     - alanine2D_HF_baseline_ICM
    array:
     - 
      namebase: alanine2D_HF_exp_
      N_experiments: 20
  
