---

sobol: # summary statistics are calculated for these
  - a1a1
  - a1b1
  - a1c1
  - b1a1
  - b1b1
  - b1c1

covariance: # covariance matrix is calculated for these and saved to the given table name
  - [alanine2D, [a1c1, a1b1, a1a1]]
  - [alanine4D, [b1c1, b1b1, b1a1]]

timings: # experiments used to summarize timing data
  - b1a1
  - b1b1
  - b1c1