---

sobol: # summary statistics are calculated for these
  - a1a1
  - a1b1
  - a1c1
  - b1a1
  - b1b1
  - b1c1

covariance: # covariance matrix is calculated for these and saved to the given table name
  - [alanine2D, [a1c1, a1b1, a1a1]]
  - [alanine4D, [b1c1, b1b1, b1a1]]

timings: # experiments used to summarize timing data
  - b1a1
  - b1b1
  - b1c1

sampling_strategies:
  - a1a4 # random uniform
  - a1a1 # sobol
  - a1a3 # BO inorder
  
baseline_convergence_speed: # plot histograms of convergence speed
  baseline_convergence_alanine2D: [a1a3, a1b2, a1c2]
  baseline_convergence_alanine4D: [b1a2, b1b2, b1c2]