---
 - # Alanine 2D HF
  true_value: [-8803.2773521]
  tolerance_levels: [0.1, 0.05, 0.02, 0.01]
  variable: gmp
  begin_row: 0
  select_cols: [-2]
  path: ~/BOSS-MT/processed_data/
  experiment_files:
   - alanine2D_HF_baseline.json
   - alanine2D_HF_baseline_ICM.json
   - alanine2D_HF_exp_1.json
   - alanine2D_HF_exp_10.json
   - alanine2D_HF_exp_11.json
   - alanine2D_HF_exp_12.json
   - alanine2D_HF_exp_13.json
   - alanine2D_HF_exp_14.json
   - alanine2D_HF_exp_15.json
   - alanine2D_HF_exp_16.json
   - alanine2D_HF_exp_17.json
   - alanine2D_HF_exp_18.json
   - alanine2D_HF_exp_19.json
   - alanine2D_HF_exp_2.json
   - alanine2D_HF_exp_20.json
   - alanine2D_HF_exp_3.json
   - alanine2D_HF_exp_4.json
   - alanine2D_HF_exp_5.json
   - alanine2D_HF_exp_6.json
   - alanine2D_HF_exp_7.json
   - alanine2D_HF_exp_8.json
   - alanine2D_HF_exp_9.json
 - # Alanine 2D LF
  true_value: [17.481530349]
  tolerance_levels: [2.3061, 1.15305, 0.46122, 0.23061]
  variable: gmp
  begin_row: 0
  select_cols: [-2]
  path: ~/BOSS-MT/processed_data/
  experiment_files:
   - alanine2D_LF_baseline.json
   - alanine2D_LF_baseline_ICM.json
   - alanine2D_LF_exp_1.json
   - alanine2D_LF_exp_10.json
   - alanine2D_LF_exp_11.json
   - alanine2D_LF_exp_12.json
   - alanine2D_LF_exp_13.json
   - alanine2D_LF_exp_14.json
   - alanine2D_LF_exp_15.json
   - alanine2D_LF_exp_16.json
   - alanine2D_LF_exp_17.json
   - alanine2D_LF_exp_18.json
   - alanine2D_LF_exp_19.json
   - alanine2D_LF_exp_2.json
   - alanine2D_LF_exp_20.json
   - alanine2D_LF_exp_3.json
   - alanine2D_LF_exp_4.json
   - alanine2D_LF_exp_5.json
   - alanine2D_LF_exp_6.json
   - alanine2D_LF_exp_7.json
   - alanine2D_LF_exp_8.json
   - alanine2D_LF_exp_9.json
 - # Alanine 4D HF
  true_value: [-8803.2801337]
  tolerance_levels: [0.1, 0.05, 0.02, 0.01]
  variable: gmp
  begin_row: 0
  select_cols: [-2]
  path: ~/BOSS-MT/processed_data/
  experiment_files:
   - alanine4D_HF_baseline.json
   - alanine4D_HF_baseline_ICM.json
   - alanine4D_HF_exp_1.json
   - alanine4D_HF_exp_10.json
   - alanine4D_HF_exp_11.json
   - alanine4D_HF_exp_12.json
   - alanine4D_HF_exp_13.json
   - alanine4D_HF_exp_14.json
   - alanine4D_HF_exp_15.json
   - alanine4D_HF_exp_16.json
   - alanine4D_HF_exp_2.json
   - alanine4D_HF_exp_3.json
   - alanine4D_HF_exp_4.json
   - alanine4D_HF_exp_5.json
   - alanine4D_HF_exp_6.json
   - alanine4D_HF_exp_7.json
   - alanine4D_HF_exp_8.json
   - alanine4D_HF_exp_9.json
 - # Alanine 4D LF
  true_value: [15.793149302]
  tolerance_levels: [2.3061, 1.15305, 0.46122, 0.23061]
  variable: gmp
  begin_row: 0
  select_cols: [-2]
  path: ~/BOSS-MT/processed_data/
  experiment_files:
   - alanine4D_LF_baseline.json
   - alanine4D_LF_baseline_ICM.json
   - alanine4D_LF_exp_1.json
   - alanine4D_LF_exp_2.json
   - alanine4D_LF_exp_3.json
   - alanine4D_LF_exp_4.json
   - alanine4D_LF_exp_5.json
   - alanine4D_LF_exp_6.json
   - alanine4D_LF_exp_7.json
   - alanine4D_LF_exp_8.json
   - alanine4D_LF_exp_9.json
   - alanine4D_LF_exp_10.json
   - alanine4D_LF_exp_11.json
   - alanine4D_LF_exp_12.json
   - alanine4D_LF_exp_13.json
   - alanine4D_LF_exp_14.json
   - alanine4D_LF_exp_15.json
   - alanine4D_LF_exp_16.json