---
# config file for computing model and cputimes for experiments

single_output:
 - # baselines and single independent experiments
  path: ~/BOSS-MT/processed_data/ # path to json files
  names: # experiment parsed data files without suffix
   - alanine2D_HF_baseline
   - alanine2D_LF_baseline
   - alanine4D_HF_baseline
   - alanine4D_LF_baseline
  single_core_time: # approximation acquisition time on single core per baseline, same order as above
   - 23
   - 0.3
   - 23
   - 0.3
 
transfer_learning:
 - # HF 2D experiments
  path: ~/BOSS-MT/processed_data/
  baselines:
   - alanine2D_HF_baseline # primary task baseline
   - alanine2D_LF_baseline # secondary task
  N_experiments: 20 # number of experiments
  namebase: alanine2D_HF_exp_
  single_core_time: 23 # primary task single core acquisition time in seconds
 - # LF 2D experiments
  path: ~/BOSS-MT/processed_data/
  baselines:
   - alanine2D_LF_baseline
   - alanine2D_HF_baseline
  N_experiments: 20
  namebase: alanine2D_LF_exp_
  single_core_time: 0.3
 - # HF 4D experiments
  path: ~/BOSS-MT/processed_data/
  baselines:
   - alanine4D_HF_baseline # primary task baseline
   - alanine4D_LF_baseline # secondary task
  N_experiments: 16 # number of experiments
  namebase: alanine4D_HF_exp_
  single_core_time: 23 # primary task single core acquisition time in seconds
 - # LF 4D experiments
  path: ~/BOSS-MT/processed_data/
  baselines:
   - alanine4D_LF_baseline
   - alanine4D_HF_baseline
  N_experiments: 16
  namebase: alanine4D_LF_exp_
  single_core_time: 0.3

  


