---
### Sobol queue experiments for correlation between tasks
unique:
  -
   path: ~/BOSS-MT/data/sobol_queue/
   json_path: ~/BOSS-MT/processed_data/sobol_queue/
   files:
    - alanine2D_HF_sobol100/boss.out
    - alanine4D_HF_sobol300/boss.out
    - alanine4D_VHF_sobol300/boss.out
    - alanine2D_LF_sobol100/boss.out
    - alanine4D_LF_sobol300/boss.out
   names:
    - alanine2D_HF_sobol
    - alanine4D_HF_sobol
    - alanine4D_VHF_sobol
    - alanine2D_LF_sobol
    - alanine4D_LF_sobol