unique: # baseline statistical tests to see if boss is reproducible
  - 
   path: ~/BOSS-MT/data/other/
   json_path: ~/BOSS-MT/processed_data/other/
   files:
    - b1/boss.out
    - b2/boss.out
   names:
    - baseline
    - baseline_reproduced