---
figures:
 - 
  path: ~/BOSS-MT/figures/
  filename: alanine_gmp_mean_convergence
  enumerate_subplots: True
  subplots: # plot all plots in 
   - # alanine 2D HF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine2D_HF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine2D_HF_exp_
      N_experiments: 20
      use_colormap: False
    unique_experiments:
      - alanine2D_HF_baseline_ICM
    xkey: initpts
    xbegin: -1
    xunit: secondary initpts
    # y
    ykey: iterations_to_convergence
    yunit: BO iterations to convergence
    ybegin: -1
    ymin: 0
    # legend
    labelrule: experiment type
    label_experiments: [19,20,21]
    legend: True
    legend_location: lower right
    # spines
    remove_top_right_spines: True
    # title
    title: iterations to 0.01 eV GMP mean convergence 