---
figures:
 - 
  path: ~/BOSS-MT/figures/
  filename: alanine2D_4D_gmp_x_last
  enumerate_subplots: True
  subplots: # plot all plots in 
   - # alanine 2D HF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine2D_HF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine2D_HF_exp_
      N_experiments: 20
      use_colormap: True
    unique_experiments:
      - alanine2D_HF_baseline_ICM
    xkey: gmp
    xcol: 0
    xunit: d4
    # y
    ykey: gmp
    ycol: 1
    ybegin: -1
    yunit: d13
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 2D HF GMP location