---
figures:
 - 
  path: ~/BOSS-MT/figures/
  filename: 4D_gmp_y_bo_iteration
  enumerate_subplots: True
  subplots: # plot all plots in 
   - 
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine4D_HF_baseline
    array_experiments:
      namebase: alanine4D_HF_exp_
      N_experiments: 3
      use_colormap: True
    #unique_experiments:
    # x
    #xkey: cputime
    #xcol: 0
    xunit: iteration
    # y
    ykey: gmp
    ycol: -2
    yunit: kcal(mol)
    # legend
    labelrule: secondary initpts
    legend: True
    legend_location: upper right
    # spines
    remove_top_right_spines: True
    # title
    title: HF GMP value
   - 
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine4D_LF_baseline
    array_experiments:
      namebase: alanine4D_LF_exp_
      N_experiments: 3
      use_colormap: True
    #unique_experiments:
    # x
    #xkey: cputime
    #xcol: 0
    xunit: iteration
    # y
    ykey: gmp
    ycol: -2
    yunit: kcal(mol)
    # legend
    labelrule: secondary initpts
    legend: True
    legend_location: upper right
    # spines
    remove_top_right_spines: True
    # title
    title: LF GMP value
  