---
figures:
 - 
  path: ~/BOSS-MT/figures/
  filename: alanine2D_4D_gmp_var_bo_iteration
  enumerate_subplots: True
  subplots: # plot all plots in 
   - # alanine 2D HF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine2D_HF_baseline
    array_experiments:
      namebase: alanine2D_HF_exp_
      N_experiments: 20
      use_colormap: True
    unique_experiments:
      - alanine2D_HF_baseline_ICM
    xunit: BO iteration
    xmax: 30
    # y
    ykey: gmp
    ycol: -1
    # legend
    labelrule: secondary initpts
    legend: True
    legend_location: upper right
    legend_title: secondary initpts
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 2D HF GMP variance
    make_subplots: [0, 8, 14, 19, 20, 21]
   - # alanine 2D LF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine2D_LF_baseline
    array_experiments:
      namebase: alanine2D_LF_exp_
      N_experiments: 20
      use_colormap: True
    unique_experiments:
      - alanine2D_LF_baseline_ICM
    xunit: BO iteration
    xmax: 30
    # y
    ykey: gmp
    ycol: -1
    ybegin: 1
    # legend
    labelrule: secondary initpts
    legend: True
    legend_location: upper right
    legend_title: secondary initpts
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 2D LF GMP variance
    make_subplots: [0, 8, 14, 19, 20, 21]
   - # alanine 4D HF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine4D_HF_baseline
    array_experiments:
      namebase: alanine4D_HF_exp_
      N_experiments: 16
      use_colormap: True
    unique_experiments:
      - alanine4D_HF_baseline_ICM
    xunit: BO iteration
    xmax: 200
    # y
    ykey: gmp
    ycol: -1
    # legend
    labelrule: secondary initpts
    legend: True
    legend_location: upper right
    legend_title: secondary initpts
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 4D HF GMP variance
    make_subplots: [0, 5, 10, 15, 16, 17]
   - # alanine 4D LF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine4D_LF_baseline
    array_experiments:
      namebase: alanine4D_LF_exp_
      N_experiments: 16
      use_colormap: True
    unique_experiments:
      - alanine4D_LF_baseline_ICM
    xunit: BO iteration
    xmax: 75
    # y
    ykey: gmp
    ycol: -1
    ybegin: 1
    # legend
    labelrule: secondary initpts
    legend: True
    legend_location: upper right
    legend_title: secondary initpts
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 4D LF GMP variance
    make_subplots: [0, 5, 10, 15, 16, 17]
   - # alanine 4D VHF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine4D_VHF_baseline
    array_experiments:
      namebase: alanine4D_VHF_exp_
      N_experiments: 16
      use_colormap: True
    unique_experiments:
      - alanine4D_VHF_baseline_ICM
    xunit: BO iteration
    xmax: 200
    # y
    ykey: gmp
    ycol: -1
    # legend
    labelrule: secondary initpts
    legend: True
    legend_location: upper right
    legend_title: secondary initpts
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 4D VHF GMP variance
    make_subplots: [0, 5, 10, 15, 16, 17]