---
figures:
 - 
  path: ~/BOSS-MT/figures/
  filename: iterations_to_alanine_gmp_mean_convergence_1E-2eV
  enumerate_subplots: True
  sharey: row
  sharex: row
  subplots: # plot all plots in 
   - # alanine 2D HF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine2D_HF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine2D_HF_exp_
      N_experiments: 20
      use_colormap: False
    unique_experiments:
      - alanine2D_HF_baseline_ICM
    xkey: initpts
    xbegin: -1
    xunit: secondary initpts
    # y
    ykey: iterations_to_convergence
    yunit: BO iterations to convergence
    ybegin: -1
    # legend
    labelrule: experiment type
    label_experiments: [19,20,21]
    legend: True
    legend_location: lower right
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 2D HF, tolerance 0.01 eV
   - # alanine 2D LF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine2D_LF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine2D_LF_exp_
      N_experiments: 20
      use_colormap: False
    unique_experiments:
      - alanine2D_LF_baseline_ICM
    xkey: initpts
    xbegin: -1
    xunit: secondary initpts
    # y
    ykey: iterations_to_convergence
    yunit: BO iterations to convergence
    ybegin: -1
    # legend
    labelrule: experiment type
    label_experiments: [19,20,21]
    legend: True
    legend_location: upper right
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 2D LF, tolerance 0.01 eV
   - # alanine 4D HF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine4D_HF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine4D_HF_exp_
      N_experiments: 16
      use_colormap: False
    unique_experiments:
      - alanine4D_HF_baseline_ICM
    xkey: initpts
    xbegin: -1
    xunit: secondary initpts
    # y
    ykey: iterations_to_convergence
    yunit: BO iterations to convergence
    ybegin: -1
    # legend
    labelrule: experiment type
    label_experiments: [15,16,17]
    legend: True
    legend_location: upper right
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 4D HF, tolerance 0.01 eV
   - # alanine 4D LF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine4D_LF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine4D_LF_exp_
      N_experiments: 16
      use_colormap: False
    unique_experiments:
      - alanine4D_LF_baseline_ICM
    xkey: initpts
    xbegin: -1
    xunit: secondary initpts
    # y
    ykey: iterations_to_convergence
    yunit: BO iterations to convergence
    ybegin: -1
    ymin: 0
    # legend
    labelrule: experiment type
    label_experiments: [15,16,17]
    legend: True
    legend_location: upper right
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 4D LF, tolerance 0.01 eV

 - 
  path: ~/BOSS-MT/figures/
  filename: cputime_to_alanine_gmp_mean_convergence_1E-2eV
  enumerate_subplots: True
  subplots: # plot all plots in 
   - # alanine 2D HF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine2D_HF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine2D_HF_exp_
      N_experiments: 20
      use_colormap: False
    unique_experiments:
      - alanine2D_HF_baseline_ICM
    xkey: initpts
    xbegin: -1
    xunit: secondary initpts
    # y
    ykey: cputime_to_convergence
    yunit: CPU time (s) to convergence
    ybegin: -1
    ymin: 0
    # legend
    labelrule: experiment type
    label_experiments: [19,20,21]
    legend: True
    legend_location: lower right
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 2D HF, tolerance 0.01 eV
   - # alanine 2D LF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine2D_LF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine2D_LF_exp_
      N_experiments: 20
      use_colormap: False
    unique_experiments:
      - alanine2D_LF_baseline_ICM
    xkey: initpts
    xbegin: -1
    xunit: secondary initpts
    # y
    ykey: cputime_to_convergence
    yunit: CPU time (s) to convergence
    ybegin: -1
    ymin: 0
    # legend
    labelrule: experiment type
    label_experiments: [19,20,21]
    legend: True
    legend_location: upper left
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 2D LF, tolerance 0.01 eV
   - # alanine 4D HF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine4D_HF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine4D_HF_exp_
      N_experiments: 16
      use_colormap: False
    unique_experiments:
      - alanine4D_HF_baseline_ICM
    xkey: initpts
    xbegin: -1
    xunit: secondary initpts
    # y
    ykey: cputime_to_convergence
    yunit: CPU time (s) to convergence
    ybegin: -1
    ymin: 0
    # legend
    labelrule: experiment type
    label_experiments: [15,16,17]
    legend: True
    legend_location: upper right
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 4D HF, tolerance 0.01 eV
   - # alanine 4D LF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine4D_LF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine4D_LF_exp_
      N_experiments: 16
      use_colormap: False
    unique_experiments:
      - alanine4D_LF_baseline_ICM
    xkey: initpts
    xbegin: -1
    xunit: secondary initpts
    # y
    ykey: cputime_to_convergence
    yunit: CPU time (s) to convergence
    ybegin: -1
    ymin: 0
    # legend
    labelrule: experiment type
    label_experiments: [15,16,17]
    legend: True
    legend_location: upper left
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 4D LF, tolerance 0.01 eV
   