---
figures:
 - 
  path: ~/BOSS-MT/figures/
  filename: alanine_gmp_mean_convergence
  enumerate_subplots: True
  subplots: # plot all plots in 
   - # alanine 2D HF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine2D_HF_baseline
    plottype: scatter
    array_experiments:
      namebase: alanine2D_HF_exp_
      N_experiments: 20
      use_colormap: False
    unique_experiments:
      - alanine2D_HF_baseline_ICM
    xkey: initpts
    xbegin: -1
    xunit: secondary initpts
    # y
    ykey: iterations_to_convergence
    yunit: BO iterations to convergence
    ybegin: 0
    yend: 1
    # legend
    labelrule: secondary initpts
    legend: False
    legend_location: 
    legend_title: secondary initpts
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 2D HF iterations to GMP mean convergence