---
figures:
 - 
  path: ~/BOSS-MT/figures/
  filename: alanine_gmp_mean_convergence
  enumerate_subplots: True
  subplots: # plot all plots in 
   - # alanine 2D HF
    # load data
    path: ~/BOSS-MT/processed_data/
    baseline: alanine2D_HF_baseline
    array_experiments:
      namebase: alanine2D_HF_exp_
      N_experiments: 20
      use_colormap: True
    unique_experiments:
      - alanine2D_HF_baseline_ICM
    xkey: iterations_to_convergence
    xunit: BO iteration
    # y
    ykey: tolerance_levels
    yunit: eV
    # legend
    labelrule: secondary initpts
    legend: True
    legend_location: upper right
    legend_title: secondary initpts
    # spines
    remove_top_right_spines: True
    # title
    title: alanine 2D HF iterations to GMP mean convergence