---
# config file for parsing boss.out files with parse_files.py

unique: # baseline and special experiments
  - 
   path: ~/BOSS-MT/data/transfer_learning/ # path to main folder
   json_path: ~/BOSS-MT/processed_data/ # where output is stored
   files:
    - alanine2D/HF2D/baseline/boss.out # filename/path from main folder to boss.out
    - alanine2D/LF2D/baseline/boss.out
    - alanine4D/HF4D/baseline/boss.out
    - alanine4D/LF4D/baseline/boss.out
    - alanine4D/VHF4D/baseline/boss.out
    # ICM baselines
    - alanine2D/HF2D/baseline_ICM/boss.out
    - alanine2D/LF2D/baseline_ICM/boss.out
    - alanine4D/HF4D/baseline_ICM/boss.out
    - alanine4D/LF4D/baseline_ICM/boss.out
    - alanine4D/VHF4D/baseline_ICM/boss.out
   names:
    - alanine2D_HF_baseline # name for experiment and json dump file
    - alanine2D_LF_baseline
    - alanine4D_HF_baseline
    - alanine4D_LF_baseline
    - alanine4D_VHF_baseline
    - alanine2D_HF_baseline_ICM
    - alanine2D_LF_baseline_ICM
    - alanine4D_HF_baseline_ICM
    - alanine4D_LF_baseline_ICM
    - alanine4D_VHF_baseline_ICM
array: # array job experiments
 - # HF 2D
  path: ~/BOSS-MT/data/transfer_learning/alanine2D/HF2D/
  N_experiments: 20 # number of similar experiments
  filebase: exp_ #filename basis that is appended with a number from 1 to N_experiments
  namebase: alanine2D_HF_exp_ # How experiment and json dump will be named
  json_path: ~/BOSS-MT/processed_data/ # where output is stored
 - # LF 2D
  path: ~/BOSS-MT/data/transfer_learning/alanine2D/LF2D/
  N_experiments: 20
  filebase: exp_
  namebase: alanine2D_LF_exp_
  json_path: ~/BOSS-MT/processed_data/
 - # HF 4D
  path: ~/BOSS-MT/data/transfer_learning/alanine4D/HF4D/
  N_experiments: 16
  filebase: exp_
  namebase: alanine4D_HF_exp_
  json_path: ~/BOSS-MT/processed_data/
 - # LF 4D
  path: ~/BOSS-MT/data/transfer_learning/alanine4D/LF4D/
  N_experiments: 16
  filebase: exp_
  namebase: alanine4D_LF_exp_
  json_path: ~/BOSS-MT/processed_data/
 - # VHF 4D
  path: ~/BOSS-MT/data/transfer_learning/alanine4D/VHF4D/
  N_experiments: 16
  filebase: exp_
  namebase: alanine4D_VHF_exp_
  json_path: ~/BOSS-MT/processed_data/
