---
# config file for parsing boss.out files with parse_files.py
array: # array job experiments
 - # 1a11
  path: ~/BOSS-MT/data/experiments/alanine2D/LF2D/1a11_sobol_queue/
  N_experiments: 30 # number of similar experiments
  filebase: exp_ #filename basis that is appended with a number from 1 to N_experiments
  namebase: 1a11_ # How experiment and json dump will be named
  json_path: ~/BOSS-MT/processed_data/ # where output is stored
 - # 1a12
  path: ~/BOSS-MT/data/experiments/1a12_baseline_sobol_init/
  N_experiments: 30
  filebase: exp_
  namebase: 1a12_
  json_path: ~/BOSS-MT/processed_data/
 - # 1b11
  path: ~/BOSS-MT/data/experiments/1b11_ICM_baseline_sobol_init/
  N_experiments: 30
  filebase: exp_
  namebase: 1b11_
  json_path: ~/BOSS-MT/processed_data/
 - # 1b12
  path: ~/BOSS-MT/data/experiments/1b12_ICM_baseline_sobol_init_kappa_0/
  N_experiments: 30
  filebase: exp_
  namebase: 1b12_
  json_path: ~/BOSS-MT/processed_data/
 - # 1b13
  path: ~/BOSS-MT/data/experiments/1b13_ICM_baseline_sobol_init_W_0/
  N_experiments: 30
  filebase: exp_
  namebase: 1b12_
  json_path: ~/BOSS-MT/processed_data/


