---
# y_offset reference value dependencies
baselines:
  a1a1: a1a1 #baseline and source for truemin / y_offset
  a1b1: a1b1

#experiments:
  

   
tolerances: [5, 2, 1,0.5,0.2,0.1,0.05,0.02,0.01,0.005,0.002,0.001]