---
# y_offset reference value dependencies
baselines:
  a1a3: a1a3
  a1a1: a1a3 #baseline and source for truemin / y_offset
  a1a2: a1a3
  a1b2: a1b2
  a1b1: a1b2
  a1c2: a1c2
  a1c1: a1c2
  b1a2: b1a2
  b1a1: b1a2
  b1b2: b1b2
  b1b1: b1b2
  b1c2: b1c2
  b1c1: b1c2

  
#experiments:
experiments:
  a2a1: 
    - a1a3
  a2a2: 
    - a1a3
  a2a3: 
    - a1a3
  a2a4: 
    - a1a3
  a2b1:
    - a1b2
  a3b1: # prior selection experiments
    - a1b2
    - a1a3
  a3b2:
    - a1b2
    - a1a3
  a3b3:
    - a1b2
    - a1a3
  a3b4:
    - a1b2
    - a1a3
  a3b5:
    - a1b2
    - a1a3
  a3b6: # TL experiments
    - a1b2
    - a1a3
  a3b7:
    - a1b2
    - a1a3
  a3c1:
    - a1c2
    - a1a3
  a3c2:
    - a1c2
    - a1b2
  a3c3:
    - a1c2
    - a1a3
  a3c4:
    - a1c2
    - a1b2
  b2c1:
    - b1c2
  b3b1:
    - b1b2
    - b1a2
  b3c1:
    - b1c2
    - b1a2
  

  
   
tolerances: [5, 2, 1,0.5,0.2,0.1,0.05,0.02,0.01,0.005,0.002,0.001]