---
### Sobol queue experiments for correlation between tasks
single_output:
  -
   path: ~/BOSS-MT/processed_data/sobol_queue/
   names:
    - alanine2D_HF_sobol
    - alanine4D_HF_sobol
    - alanine4D_VHF_sobol
    - alanine2D_LF_sobol
    - alanine4D_LF_sobol
   single_core_time: # approximation of mean acquisition time on single core per baseline, same order as above
    - 23
    - 23
    - 51
    - 0.3
    - 0.3
   get_truemin_from:
    - self # experiment is self a baseline
    - self
    - self
    - self
    - self
   rescale_by: # rescale energy to kcal/mol
    - 23.061
    - 23.061
    - 23.061
    - 1
    - 1