---
# y_offset reference value dependencies
baselines:
  a1a3: a1a3
  a1a1: a1a3 #baseline and source for truemin / y_offset
  a1a2: a1a3
  a1a4: a1a3
  a1b2: a1b2
  a1b1: a1b2
  a1b3: a1b2
  a1c2: a1c2
  a1c1: a1c2
  b1a2: b1a2
  b1a1: b1a2
  b1b2: b1b2
  b1b1: b1b2
  b1c2: b1c2
  b1c1: b1c2

  
#experiments:
# experiment name
# baseline, initialization strategy (self, random, inorder)
# secondary source, initialization strategy (self, random, inorder)
experiments:
  a2a1: 
    - [a1a3, self]
  a2a2: 
    - [a1a3, self]
  a2a3: 
    - [a1a3, self]
  a2a4: 
    - [a1a3, self]
  a2b1:
    - [a1b2, self]
  a3b1: # prior selection experiments
    - [a1b2, random]
    - [a1a3, random]
  a3b2:
    - [a1b2, random]
    - [a1a3, random]
  a3b3:
    - [a1b2, random]
    - [a1a3, random]
  a3b4:
    - [a1b2, random]
    - [a1a3, random]
  a3b5:
    - [a1b2, random]
    - [a1a3, random]
  a3b6: # TL experiments
    - [a1b2, random]
    - [a1a3, self]
  a3b7:
    - [a1b2, random]
    - [a1a3, inorder]
  a3b8:
    - [a1b2, random]
    - [a1a1, random]
  a3b9:
    - [a1b2, random]
    - [a1a4, random]
  a3c1:
    - [a1c2, random]
    - [a1a3, self]
  a3c2:
    - [a1c2, random]
    - [a1b2, self]
  a3c3:
    - [a1c2, random]
    - [a1a3, inorder]
  a3c4:
    - [a1c2, random]
    - [a1b2, inorder]
  a3c5:
    - [a1c2, random]
    - [a1a1, random]
  a3c6:
    - [a1c2, random]
    - [a1b1, random]
  a3c7:
    - [a1c2, random]
    - [a1a4, random]
  a3c8:
    - [a1c2, random]
    - [a1b3, random]
  b2c1:
    - [b1c2, self]
  b3b1:
    - [b1b2, random]
    - [b1a2, inorder]
  b3b2:
    - [b1b2, random]
    - [b1a2, self]
  b3c1:
    - [b1c2, random]
    - [b1a2, inorder]
  b3c2:
    - [b1c2, random]
    - [b1b2, inorder]
  b3c3:
    - [b1c2, random]
    - [b1a2, self]
  b3c4:
    - [b1c2, random]
    - [b1b2, self]

   
tolerances: [5, 2, 1,0.5,0.2,0.1,0.05,0.02,0.01,0.005,0.002,0.001]