single_output:
 - # baseline experiments to see if boss is reproducible
  path: ~/BOSS-MT/processed_data/other/ # path to json files
  names: # experiment parsed data files without suffix
   - baseline
   - baseline_reproduced
  single_core_time: # approximation of mean acquisition time on single core per baseline, same order as above
   - 0.3
   - 0.3
  get_truemin_from:
   - self # experiment is self a baseline
   - self
  rescale_by: # rescale energy to kcal/mol
   - 1
   - 1