---
# y_offset reference value dependencies
baselines:
  a1a3: a1a3
  a1a2: a1a3 #baseline and source for truemin / y_offset
  a1b2: a1a3

experiments:
  a1a1:
   - a1a3 # experiment and sources for truemin / y_offset
  a1b1:
   - a1b2
  a2a1:
   - a1a3
  a2b1:
   - a1b2
  a2a2: 
   - a1a3
  a2b2: 
   - a1b2
  a2a3: 
   - a1a3
  a2b3: 
   - a1b2
  a2a4:
   - a1a3
  a2a5:
   - a1a3

   
tolerances: [5, 2, 1,0.5,0.2,0.1,0.05,0.02,0.01,0.005,0.002,0.001]