---
# y_offset reference value dependencies
baselines:
  a1a2: a1a2 #baseline and source for truemin / y_offset
  a1b2: a1b2

experiments:
  a1a1: 
    - a1a2 # experiment and sources for truemin / y_offset
  a1b1: 
    - a1b2
  a2a1: 
    - a1a2
  a2b1: 
    - a1b2
  a2a2: 
    - a1a2
  a2b2: 
    - a1b2
  a2a3: 
    - a1a2
  a2b3: 
    - a1b2



